# Generated by Django 2.2 on 2023-03-08 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operation', '0002_arnab_العمر'),
    ]

    operations = [
        migrations.AddField(
            model_name='arnab',
            name='hh',
            field=models.ImageField(default='dd', upload_to=''),
            preserve_default=False,
        ),
    ]
