# Generated by Django 2.2 on 2023-03-11 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operation', '0007_arnaba_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='arnaba',
            name='image',
            field=models.CharField(default='arnaba.png', max_length=200),
        ),
    ]
