# Generated by Django 4.2.1 on 2023-07-08 19:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('operation', '0011_alter_arnaba_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='arnaba',
            old_name='مرات_التلقيح',
            new_name='talqeeh_times',
        ),
    ]
