# Generated by Django 4.2.1 on 2023-07-09 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operation', '0012_rename_مرات_التلقيح_arnaba_talqeeh_times'),
    ]

    operations = [
        migrations.AlterField(
            model_name='arnaba',
            name='state',
            field=models.CharField(choices=[('fadya', 'fadya'), ('malyana', 'malyana'), ('Metlaqa7a', 'Metlaqa7a'), ('Morde3a', 'Morde3a'), ('7amel w Morde3a', '7amel w Morde3a'), ('Metlaqa7a w Morde3a', 'Metlaqa7a w Morde3a')], default='fadya', max_length=200),
        ),
    ]
