# Generated by Django 4.2.1 on 2023-07-09 07:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('operation', '0013_alter_arnaba_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='arnaba',
            name='talqeeh_zakar',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='operation.arnab'),
            preserve_default=False,
        ),
    ]
