# Generated by Django 4.2.1 on 2023-07-09 07:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('operation', '0014_arnaba_talqeeh_zakar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='arnaba',
            name='talqeeh_zakar',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='operation.arnab'),
        ),
    ]
