# Generated by Django 4.2.1 on 2023-07-09 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operation', '0015_alter_arnaba_talqeeh_zakar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='arnab',
            name='name',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
