# Generated by Django 4.2.1 on 2023-07-09 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operation', '0017_arnab_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='arnaba',
            name='birth_date',
        ),
        migrations.AddField(
            model_name='arnaba',
            name='age',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
