# Generated by Django 4.2.1 on 2023-07-10 09:47

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('operation', '0020_arnaba_talqeeh_zakar'),
    ]

    operations = [
        migrations.AddField(
            model_name='arnaba',
            name='talqeeh_timestamp',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
