# Generated by Django 4.2.1 on 2023-07-10 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operation', '0021_arnaba_talqeeh_timestamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='arnaba',
            name='talqeeh_timestamp',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
