# Generated by Django 4.2.1 on 2023-07-10 10:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operation', '0022_alter_arnaba_talqeeh_timestamp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='arnaba',
            name='talqeeh_timestamp',
        ),
        migrations.AddField(
            model_name='arnaba',
            name='talqeeh_datestamp',
            field=models.DateField(default=datetime.date(2023, 7, 10)),
        ),
    ]
